name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          ACCUWEATHER_KEY: ${{ secrets.ACCUWEATHER_KEY }}
          WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}
        run: ./gradlew build --no-daemon

      - name: Build Debug APK
        env:
          ACCUWEATHER_KEY: ${{ secrets.ACCUWEATHER_KEY }}
          WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
